version: "3.8"

services:
  geth-poa:
    image: ethereum/client-go:v1.12.0
    container_name: geth-poa
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "30305:30303/tcp"
      - "30305:30303/udp"
    volumes:
      - ./poa-data:/data
    command: >
      --datadir /data
      --networkid 2078
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api admin,eth,net,web3,personal,txpool,miner,clique
      --http.vhosts="*"
      --http.corsdomain="*"
      --allow-insecure-unlock
      --unlock 0xYourWalletAddressHere
      --miner.etherbase 0xYourWalletAddressHere
      --password /data/password.txt
      --mine
      --miner.gasprice "1000000000"
      --syncmode full
      --snapshot=false
      --maxpeers 30
      --nodiscover
    # Uncomment baris berikut jika ingin menambahkan IP eksternal manual:
    #   --nat extip:192.168.x.x
